# Generated by Django 4.2.7 on 2023-12-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_stand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stand',
            new_name='Land',
        ),
    ]
